### ISSUE TITLE
Moving this resolver to the sceptre org?

### ISSUE THREAD

**Issue by craighurley** [Sceptre/sceptre-resolver-cmd#3]
Hi Luke,

Thanks for making this useful resolver.  Would you support moving this resolver to the sceptre org?

**Comment by lukeplausin** [comment]
Hi Craig,

I'm glad you've found it useful. I've moved the resolver into the Sceptre org now 👍

**Comment by craighurley** [comment]
Thanks Luke. Will the sceptre org also have the ability to publish to the existing pypi module name or will they have to publish under a different module name?

**Comment by craighurley** [comment]
Hi @lukeplausin do you think you can give ownership of the module on pypi to one of the maintainers of sceptre?

https://pypi.org/help/#request-ownership

**Comment by lukeplausin** [comment]
Hi @craighurley, yes I'd be happy to invite yourself and @zaro0508  as owners. What are your usernames on PyPI?

**Comment by craighurley** [comment]
Thanks Luke; it's probably better to add the `sceptre` user on pypi rather than a named individual:

https://pypi.org/user/sceptre/

@zaro0508 let us know if you agree?

**Comment by zaro0508** [comment]
@lukeplausin It would be helpful if you could add me so i can test initial deployments with my own account.  https://pypi.org/user/zaro0508/
thanks.

**Comment by lukeplausin** [comment]
I've invited both users as owners
